// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNayBbz2D7ckYHIk9t1iG-HjDTXVHk2Ko',
    appId: '1:538344358121:web:79d7023b211ade9fb87078',
    messagingSenderId: '538344358121',
    projectId: 'flutter-app-425d4',
    authDomain: 'flutter-app-425d4.firebaseapp.com',
    storageBucket: 'flutter-app-425d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxo7hOu_LoIwDcTxImzEWnLquHArIXoD0',
    appId: '1:538344358121:android:2d7da1acaf69c730b87078',
    messagingSenderId: '538344358121',
    projectId: 'flutter-app-425d4',
    storageBucket: 'flutter-app-425d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQzAPnPH9NZ51aOABAXtUXBI8Yp0FwY-A',
    appId: '1:538344358121:ios:b2bb924fafe7b389b87078',
    messagingSenderId: '538344358121',
    projectId: 'flutter-app-425d4',
    storageBucket: 'flutter-app-425d4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQzAPnPH9NZ51aOABAXtUXBI8Yp0FwY-A',
    appId: '1:538344358121:ios:9b06481f577d1615b87078',
    messagingSenderId: '538344358121',
    projectId: 'flutter-app-425d4',
    storageBucket: 'flutter-app-425d4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
